name: Build Rust
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-linux-android

      - name: Build
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git
          cd lib && cross build --target aarch64-linux-android --release

      - name: Package
        run: |
          SHA=$(git rev-parse --short=7 HEAD)
          mkdir -p dist/lib
          cp lib/target/aarch64-linux-android/release/setup dist/lib/setup
          cp module/customize.sh dist/
          chmod +x dist/lib/setup
          echo "ARTIFACT_NAME=simple-setup+$SHA" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/
          archive: false